### ISSUE TITLE
Sealed classes not parsed

### ISSUE THREAD

**Issue by FlorentSimonnot** [kbuntrock/openapi-maven-plugin#105]
There is an error with sealed class.

<img width="1616" alt="Capture d’écran 2023-12-13 à 18 03 50" src="https://github.com/kbuntrock/openapi-maven-plugin/assets/49518183/117fae18-55dd-4a83-889f-91e71e4eb2f7">

**Comment by kbuntrock** [comment]
Thank you for the report, will have a look at it.

Do you confirm using the last version? (0.0.17)

**Comment by FlorentSimonnot** [comment]
Yep I use the last version

**Comment by kbuntrock** [comment]
Resolved, will be shipped in 0.0.18. Javaparser seams not quite perfect with sealed class, but it should fix your issue.
