### ISSUE TITLE
Allow setting the title, version and servers through configuration

### ISSUE THREAD

**Issue by royteeuwen** [kbuntrock/openapi-maven-plugin#107]
I'm trying to expand the generation of API specs to multiple files, but this does not work correctly. When generating one API spec, you can use the <freeFields> to specify the server urls. But if you would go to multiple API files based on the <apis> tag, where you typically want another title + version per file, you would have to redefine the server urls as well every time, because it overrides the entire freeFields of the generic configuration.

To mitigate this, I think it would be nice to have the title, version and servers as minimum to be able to configure as separate configuration fields, instead of using the freeFields

**Comment by royteeuwen** [comment]
@kbuntrock  I have created an initial PR, could you review and see if you agree :)?

**Comment by kbuntrock** [comment]
Hello @royteeuwen.

I'm scared that this solution will not "scale" well. In the future, someone can come with the same request for another field.

What do you think about a configuration to merge the json in the freeField section instead of a global replacement?

**Comment by royteeuwen** [comment]
I think the title, version and servers is a real global use case, but merging is the second best alternative for me 😄 better than the current situation

**Comment by kbuntrock** [comment]
I have pushed some code allowing a merge between the common and specific api configuration.
Could you try if it fits your needs?

An example of the configuration can be found in an integration test : 
- the pom : https://github.com/kbuntrock/openapi-maven-plugin/pull/113/files#diff-9d61bb28842582307fde3f0a0640838bd124ea9da9dcc97a30536a52afe5903f
- the merged file : https://github.com/kbuntrock/openapi-maven-plugin/pull/113/files#diff-62a0ae4ad2c3aa207a460a95709dfd4a1ba345706560d9813c48d57e91fba50a

**Comment by royteeuwen** [comment]
Looks good to me! can you create a release?

**Comment by kbuntrock** [comment]
Perfect :)

I will release when all on-going bugs and enhancement PRs are merged. In term of planning, it should be mid-february.

**Comment by kbuntrock** [comment]
Done, will be shipped on 0.0.18
