### ISSUE TITLE
Add support for Jackson @JsonProperty

### ISSUE THREAD

**Issue by hugop95** [kbuntrock/openapi-maven-plugin#116]
`@JsonProperty("isPlugged")
        private boolean plugged;`

generates

`plugged:
    type: boolean`

Would there be any possibility to support this Jackson annotation?

**Comment by kbuntrock** [comment]
It's possible. Difficulty reside if we fully support this annotation (not only on fields but also on methods).

I'll focus first on fields.

**Comment by hugop95** [comment]
> It's possible. Difficulty reside if we fully support this annotation (not only on fields but also on methods).
> 
> I'll focus first on fields.

Thanks, I had some free time and created a pull request handling fields if you are interested.
