### ISSUE TITLE
Rest controllers without @RequestMapping ignored

### ISSUE THREAD

**Issue by evernat** [kbuntrock/openapi-maven-plugin#13]
https://github.com/kbuntrock/openapi-maven-plugin/blob/3669979ca7be7ad599d9af0ee12e960a242bf417/src/main/java/com/github/kbuntrock/SpringResourceParser.java#L43

hmm, rest controllers may not have `@RequestMapping` annotation.
Rest methods may have `@RequestMapping(value = "...", method = RequestMethod.GET)` or `@GetMapping("...")` directly.

For example :
https://github.com/spring-petclinic/spring-petclinic-microservices/blob/master/spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/web/VisitResource.java

**Comment by kbuntrock** [comment]
Thank you for the report. Done and tested. :)
