### ISSUE TITLE
Not compatible with java 8

### ISSUE THREAD

**Issue by evernat** [kbuntrock/openapi-maven-plugin#14]
https://github.com/kbuntrock/openapi-maven-plugin/blob/3669979ca7be7ad599d9af0ee12e960a242bf417/pom.xml#L36

According to my stats, 66% of java apps and so many java devs still use Java 8.

They will not be able to use the plugin without using Java 11.

**Comment by kbuntrock** [comment]
Good advice and done. I did not create any integration test for it, but I keep this in mind.
