### ISSUE TITLE
Support JSON output

### ISSUE THREAD

**Issue by dantheperson** [kbuntrock/openapi-maven-plugin#141]
We have some existing toolling that requires a JSON spec file, so would lke to output JSON rather than YAML.

I have created a PR for this https://github.com/kbuntrock/openapi-maven-plugin/pull/140

**Comment by kbuntrock** [comment]
Thank you for this PR. I commented a few reviews.

**Comment by kbuntrock** [comment]
Merged and added #146 to complete your PR @dantheperson 

Thank you for your contribution 🙏
