### ISSUE TITLE
Failure on Parameter Object

### ISSUE THREAD

**Issue by dantheperson** [kbuntrock/openapi-maven-plugin#142]
```java
@GetMapping(produces = APPLICATION_JSON_VALUE)
public ResponseEntity<?> getAllUserShippingAddresses(B2cShippingAddressSearchFilterDto filter){

}
``` 

Results in a ConcurrentModificationException In SpringMvcReader as we loop `parameters` with a `forEach` and then pass them to `bindDtoToQueryParams` which modifies the Map.

I;'ll do a PR to fix.

**Comment by kbuntrock** [comment]
Thank you 🙏

**Comment by dantheperson** [comment]
actually my example above is incorrect, you already have a test case, but the issue is only triggered when there are mulitple parameters and you insert into the Map and then continue iterating.  Anyway i added a test case on the PR to illustrate.
