### ISSUE TITLE
Consider using ClassGraph in replacement of Reflections

### ISSUE THREAD

**Issue by murdos** [kbuntrock/openapi-maven-plugin#166]
This plugin heavily relies on [Reflections](https://github.com/ronmamo/reflections), however this library is not [maintained](https://github.com/ronmamo/reflections/issues/465)

[ClassGraph](https://github.com/classgraph/classgraph) provides similar functionality, but is actively maintained, has frequent releases, and is widely used.

**Comment by kbuntrock** [comment]
I did not know this library. Looks nice and maybe can even simplify the process of scanning in the Plexus classloader used by maven.

I'm up for it.
