### ISSUE TITLE
Add JDK 21 to build in CI

### ISSUE THREAD

**Issue by murdos** [kbuntrock/openapi-maven-plugin#172]
Each LTS version should be tested, or at least the active ones :)

**Comment by kbuntrock** [comment]
Are you referring to the name of the docker image? Currently, I'm (normally) already checking java 21 : 

![image](https://github.com/user-attachments/assets/da4bb7a1-19e5-4a65-9ad6-8a799d7f74a7)

But I have to admit, I wrongly named my docker image and I was too lazy to change its name : https://github.com/kbuntrock/docker-mvn-jdk-8-11-17

**Comment by murdos** [comment]
Oh, my bad! 
Indeed I've been confused by the docker image name :D
