### ISSUE TITLE
How to make java.sql.Timestamp return String  

### ISSUE THREAD

**Issue by yswtrue** [kbuntrock/openapi-maven-plugin#174]
java.sql.Timestamp will generate Timestamp interface even though add JsonFormat annotation, how can I specific to use string class
![CleanShot 2024-09-18 at 20 59 05@2x](https://github.com/user-attachments/assets/308edcc2-0a54-4445-91b2-463e46b57437)
![CleanShot 2024-09-18 at 21 00 02@2x](https://github.com/user-attachments/assets/93c6dfb4-e026-4b7c-8694-900a1f003b73)

**Comment by murdos** [comment]
Should be fixed by https://github.com/kbuntrock/openapi-maven-plugin/pull/175

Meanwhile, you can customize the modelAssociations, as described in the documentation: https://kbuntrock.github.io/openapi-maven-plugin/#/configuration?id=modelsassociations
