### ISSUE TITLE
Documenting Class<? extends SOMETHING> breaks the plugin

### ISSUE THREAD

**Issue by JonasCir** [kbuntrock/openapi-maven-plugin#54]
Hey, thanks for picking up the slack. This seems to be the only maintained maven plugin for generating openapi docs by now!

I tried it with my project and it errors with: 
```
Execution documentation of goal io.github.kbuntrock:openapi-maven-plugin:0.0.12:documentation failed:
Type ? super T (+WildcardTypeImpl is not supported yet
```

I debugged the code with `mvnDebug` and learned that the following code in my project causes the problem:

```java
public abstract class CriteriaWithDateType extends BaseCriteria {

	private final Class<? extends CriteriaDateType> dateTypeClass;

	public CriteriaWithDateType(Class<? extends CriteriaDateType> dateTypeClass) {
		this.dateTypeClass = dateTypeClass;
	}
// --- SNIP ---
}
```

 `Class` is inspected i.e., `exploreDataObject`  is called with a `DataObject` where its `javaClass` is set to `java.lang.Class`. The result is quite interesting, but I argue that everything under `java.lang.*` should not be inspected in general. It descends through `Class` until it hits the following code:
```java
package java.lang.ref;

public abstract class Reference<T> {
    private T referent;
    volatile ReferenceQueue<? super T> queue;
```
where the inspection dies as `? super T` is not supported yet.

**Comment by kbuntrock** [comment]
Oh god @JonasCir, so sorry for ghosting your message, I did not saw it. I will investigate it asap!

**Comment by kbuntrock** [comment]
Hello @JonasCir ,

May I ask you a bit more about your usecase? I would like to know if the class "CriteriaWithDateType" is used "as such" as a return or a parameter type of your webservice. Or if it is wrapped in an object defining the real implementation of CriteriaDateType?

Thank you by advance. :)

**Comment by kbuntrock** [comment]
Hello @JonasCir. To keep you updated: I had a look yesterday night at the Sormas project and started working on the fix.

**Comment by kbuntrock** [comment]
This should be fixed, will post a PR on your project to test it.

**Comment by JonasCir** [comment]
Hi @kbuntrock ,
sorry for getting back to you so late! 
I am not longer involved with the other project, so I didn't follow up on details.

The project uses `io.swagger.core.v3.swagger-maven-plugin` which appears to work now.

I really appreciate you work! Thank you for resolving this issue :)

**Comment by kbuntrock** [comment]
No worries at all @JonasCir. This bug report and the link to the Sormas project helped me a lot to improve this plugin.

Don't hesitate if you find some more or if you have some evolution ideas! ;)

Wish you a great day.

**Comment by JonasCir** [comment]
Great thanks :)
