### ISSUE TITLE
Allow using other NotNull annotations

### ISSUE THREAD

**Issue by royteeuwen** [kbuntrock/openapi-maven-plugin#78]
In our project we use the jetbrains annotations to specify NotNull. It would be convenient to either also support these, or to make a configuration available to specify the class name of what you want to use as NotNull annotations

**Comment by kbuntrock** [comment]
That is indeed a good idea. I'm currently in holidays for 3 weeks but I will add it as soon as I'm back.

**Comment by kbuntrock** [comment]
Back from holidays, will work on it asap. :) @royteeuwen

**Comment by josve** [comment]
Here is a suggested PR that adds support for this.

https://github.com/kbuntrock/openapi-maven-plugin/pull/111
