### ISSUE TITLE
Servers.url

### ISSUE THREAD

**Issue by magx2** [kbuntrock/openapi-maven-plugin#97]
Open API contains `server` object: https://swagger.io/specification/

Can I somehow pass it in the plugin?

**Comment by kbuntrock** [comment]
Yes, you can pass it with the "freeFields" configuration : https://kbuntrock.github.io/openapi-maven-plugin/#/configuration?id=freefields

It is possible to write the json directly in the pom.xml (allow to inject maven properties) or it can be written in a dedicated json file (cleaner).

Does it fit your needs?

PS : For this kind of questions, I guess we could use the "Discussions" github functionality : https://github.com/kbuntrock/openapi-maven-plugin/discussions
Specially the "Q&A" section (not used yet but I think thread creation is allowed for everyone, don't hesitate to tell me if not).

**Comment by magx2** [comment]
Just to be sure - it will also work with YML, right?

**Comment by magx2** [comment]
OK, works
